apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: imageswap-webhook
webhooks:
  - name: imageswap-webhook
    clientConfig:
      service:
        name: imageswap-webhook-svc
        namespace: default
        path: "/"
      caBundle: $CA_BUNDLE
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "apps"
        apiVersions:
          - "*"
        resources:
          - "deployments"
          - "statefulsets"
          - "daemonsets"
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        imageswap: "enabled"
